### ISSUE TITLE
How do you activate the dropdown menu inside code?

### ISSUE THREAD

**Issue by mintyc** [PolyMeilex/vscode-rust-targets#1]
Illustration shown for dropdown box but not clear how to get the dropdown on screen - a particular key sequence or a particular context?

**Comment by PolyMeilex** [comment]
1. Using a command palet (ctrl+shift+p)
![img](https://i.imgur.com/7Z6yGoe.png)
2. Using a button
![img](https://i.imgur.com/j17UYoe.png)

**Comment by mintyc** [comment]
Thank you - wasn't in a rust project at the time.

**Comment by PolyMeilex** [comment]
Sure, no problem.
The extension starts up only when rust files are detected, to save up some performance
